In [25]:
import numpy as np 
import pandas as pd
df=pd.read_csv('Cupcakes vs Muffins.csv')
df
df1=df.dropna()

In [26]:
df1.dtypes

Type              object
Flour              int64
Milk             float64
Sugar            float64
Butter             int64
Egg                int64
Baking Powder      int64
Vanilla            int64
Salt               int64
dtype: object

In [27]:
df_enc = pd.get_dummies(df1, columns=['Type'],drop_first=True)
df_enc

Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt  Type_Muffin
0      55  28.0    3.0       7    5              2        0     0            1
1      47  24.0   12.0       6    9              1        0     0            1
4      50  25.0   12.0       6    5              2        1     0            1
5      55  27.0    3.0       7    5              2        1     0            1
6      54  27.0    7.0       5    5              2        0     0            1
7      47  26.0   10.0      10    4              1        0     0            1
8      50  17.0   17.0       8    6              1        0     0            1
9      50  17.0   17.0      11    4              1        0     0            1
10     39   0.0   26.0      19   14              1        1     0            0
11     42  21.0   16.0      10    8              3        0     0            0
12     34  17.0   20.0      20    5              2        1     0            0
13     39  13.0   17.0      19   10              1        1     0            0
14     38  15.0   23.0      15    8              0        1     0            0
16     36  14.0   21.0      14   11              2        1     0            0
17     38  15.0   31.0       8    6              1        1     0            0
18     36  16.0   24.0      12    9              1        1     0            0
19     34  17.0   23.0      11   13              0        1     0            0

In [28]:
X=df_enc.drop('Type_Muffin',axis=1)
y=df_enc['Type_Muffin']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)
#SUPPORT VECTOR CALSSIFIER
from sklearn.svm import SVC
classification_rbf=SVC(kernel='rbf')
classification_rbf.fit(X_train,y_train)
classification_rbf.score(X_test,y_test)

1.0

In [29]:
pred=classification_rbf.predict(X_test)

In [30]:
y_test

7     1
1     1
12    0
4     1
Name: Type_Muffin, dtype: uint8

In [31]:
import joblib
joblib.dump(classification_rbf,'cupcake')
model=joblib.load('cupcake')

In [32]:
model.predict(X_train)

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1], dtype=uint8)

In [33]:
reciepie=np.array([55,28.0,3.0,7,5,2,0,0])
reciepie.reshape(-1, 1)

array([[55.],
       [28.],
       [ 3.],
       [ 7.],
       [ 5.],
       [ 2.],
       [ 0.],
       [ 0.]])

In [34]:
model.predict([[55,28.0,3.0,7,5,2,0,0]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=uint8)

In [35]:
model.predict([reciepie])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=uint8)

In [36]:
if model.predict([reciepie])==1:
  print('its a muffin')
else:
  print("cupcake")


its a muffin


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
